/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edt5y6tacondeoro;

import edt5tacondeoro1.Articulo;
import edt5tacondeoro1.LineaPedido;
import edt5tacondeoro1.Pedido;
import edt5tacondeoro1.Socio;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class Indentificacionsoc extends javax.swing.JDialog {

    private HacerPedido mipadre = null;
    private SistemaVP origen = null;

    /**
     * Creates new form Indentificacionsoc
     *
     * @param parent
     * @param modal
     */
    public Indentificacionsoc(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        parent.setVisible(false);
        mipadre = (HacerPedido) parent;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_crear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txf_cod = new javax.swing.JTextField();
        btn_selecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Si no tenias cuenta crea una");

        btn_crear.setText("Crear socio");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        jLabel2.setText("Si ya eras socio  mete su codigo y dale al boton");

        txf_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_codActionPerformed(evt);
            }
        });

        btn_selecionar.setText("Seleccionar mi socio");
        btn_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearActionPerformed

    private void txf_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_codActionPerformed
        // TODO add your handling code here:
        //if(txf_cod.getText() "existe en la BDD")
        //{btn_selecionar.setEnabled(true);
        //}
    }//GEN-LAST:event_txf_codActionPerformed

    private void btn_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionarActionPerformed
        // TODO add your handling code here:
        int codSocio = Integer.parseInt(txf_cod.getText().trim());
        boolean existe = comprobacionSocio(codSocio);
        if (existe == true) {
            ArrayList lineaPedido = getLineaPedido();
            Socio socioT = getSocio(codSocio);
            Pedido nuevoPedido = new Pedido(socioT, lineaPedido);
        }
        

    }//GEN-LAST:event_btn_selecionarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        mipadre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Indentificacionsoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Indentificacionsoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Indentificacionsoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Indentificacionsoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Indentificacionsoc dialog = new Indentificacionsoc(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public boolean comprobacionSocio(int codSocio) {
        Statement s = null;
        ResultSet rs = null;
        Boolean salida = false;
        Connection co = (Connection) origen.hazConexion();
        try {
            s = co.createStatement();
            rs = s.executeQuery("select codSocio from socio");
            //rs= s.executeQuery("select codSocio, from socio where codSocio="+"'"+codSocio+"'");
            while (rs.next()) {
                int codSocioTemp = (int) rs.getObject(1);
                if (codSocioTemp == codSocio) {
                    salida = true;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Indentificacionsoc.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                s.close();
                co.close();
            } catch (SQLException ex) {
                Logger.getLogger(Indentificacionsoc.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return salida;
    }

    public Articulo getArticuloCarrito(String nomArticulo) {

        Articulo artTemp = null;

        Statement s = null;
        ResultSet rs = null;
        Connection co = null;

        co = SistemaVP.hazConexion();
        try {
            s = co.createStatement();
            rs = s.executeQuery("select codArticulo, nombre, precio, descripcion, material, tipo, stock from articulo where nombre='" + nomArticulo + "'");
            while (rs.next()) {
                Object[] fila = new Object[7];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                fila[2] = rs.getObject(3);
                fila[3] = rs.getObject(4);
                fila[4] = rs.getObject(5);
                fila[5] = rs.getObject(6);
                fila[6] = rs.getObject(7);
                artTemp = new Articulo((int) fila[0], (String) fila[1], (float) fila[2], (String) fila[3], (String) fila[4], (String) fila[5], (int) fila[6]);
            }
        } catch (SQLException ex) {
            System.out.println("Error. " + ex.getMessage());
        } finally {
            try {
                s.close();
                co.close();
            } catch (SQLException ex) {
                Logger.getLogger(HacerPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        return artTemp;
    }

    public ArrayList getLineaPedido() {
        ArrayList lineaPed = null;
        LineaPedido lineaTemp = null;
        Articulo articulo;
        int ctd = 0;

        for (int i = 0; i < mipadre.dtmCarrito.getRowCount(); i++) {
            articulo = getArticuloCarrito((String) mipadre.dtmCarrito.getValueAt(i, 0));
            ctd = (int) mipadre.dtmCarrito.getValueAt(i, 2);
            lineaTemp = new LineaPedido(articulo, ctd);
            lineaPed.add(lineaTemp);
        }

        return lineaPed;
    }

    public Socio getSocio(int idSocio) {

        Socio socTemp = null;

        Statement s = null;
        ResultSet rs = null;
        Connection co = null;

        co = SistemaVP.hazConexion();
        try {
            s = co.createStatement();
            rs = s.executeQuery("select codSocio, nombre, correoE, direccion, poblacion where codSocio=" + idSocio);
            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                fila[2] = rs.getObject(3);
                fila[3] = rs.getObject(4);
                fila[4] = rs.getObject(5);
                socTemp = new Socio((int) fila[0], (String) fila[1], (String) fila[2], (String) fila[3], (String) fila[4]);
            }
        } catch (SQLException ex) {
            System.out.println("Error. " + ex.getMessage());
        } finally {
            try {
                s.close();
                co.close();
            } catch (SQLException ex) {
                Logger.getLogger(HacerPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        return socTemp;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_selecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txf_cod;
    // End of variables declaration//GEN-END:variables
}
